spring:
  zipkin:
    base-url: http://192.168.1.200:9411/
    sleuth:
      sampler:
        probability: 1

  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: false
      max-file-size: 10MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://38.242.196.215:3306/fudzo?createDatabaseIfNotExist=true&useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=Africa/Harare
    username: 'root'
    password: ''
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
      maximum-pool-size: 10

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    database: MYSQL
    hibernate:
      ddl-auto: update
    #      hbm2ddl:
    #       auto: update

    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.jdbc.batch_size: 500
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
      hibernate.hbm2ddl.auto: update
  data:
    jpa:
      repositories:
        bootstrap-mode: lazy

  second:
    datasource:
      type: com.zaxxer.hikari.HikariDataSource
      password: ch@ng3itDev
      username: developer
      url: jdbc:mysql://38.242.196.215:3306/fudzo_users
      driver-class-name: org.mariadb.jdbc.Driver
    jpa:
      database-platform: org.hibernate.dialect.MariaDB103Dialect
      database: MYSQL
      hibernate:
        ddl-auto: update

  jackson:
    serialization:
      fail-on-empty-beans: false
springdoc:
  swagger-ui:
    path: /swagger-ui.html
server:
  port: 9301

security:
  oauth2:
    resource:
      jwt:
        key-value: JWTKey@123
        key-uri: http://localhost:9090/oauth/token_key
      id: 'carInventory'
    client:
      client-id: appclient
      client-secret: appclient@123

logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql: TRACE

logging.logstash:
  enabled: true
  url: 62.171.154.168:5601

agent.url: http://localhost:8101
user.url: http://localhost:8202


sms.country: Zimbabwe
sms.currency: ZWL
sms.ussd: 234#
sms.senderid: Metbank
sms.url: https://api.messaging-service.com/sms/1/text/single
sms.username: METBMPOS1
sms.password: #M3tb@nk
sms.website: www.cashmet.co.zw
hsm.url: "url"

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.185:8761/eureka