eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
    instance:
        prefer-ip-address: true
    server:
        wait-time-in-ms-when-sync-empty: 0
server:
    port: ${PORT:8761}
spring:
    application:
        name: registry-service
