management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
    lease:
      duration: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

info:
  app:
    name: User-service
    version: '1.0'
    description: API for user-service on the Cloud-ID platform.
spring:
  main:
    allow-bean-definition-overriding: 'true'
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://38.242.196.215:3306/fudzo?createDatabaseIfNotExist=true&useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=Africa/Harare
    username: ''
    password: 'root'
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
      maximum-pool-size: 10

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    database: MYSQL
    hibernate:
      ddl-auto: update

    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.jdbc.batch_size: 500
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
  data:
    jpa:
      repositories:
        bootstrap-mode: lazy

  jackson:
    serialization:
      fail-on-empty-beans: false
  zipkin:
    base-url: http://localhost:9411/
    sleuth:
      sampler:
        probability: 1
  sleuth:
    sampler:
      probability: '1'
  servlet:
    multipart:
      max-file-size: 100MB
springdoc:
  swagger-ui:
    path: /swagger-ui.html
logging:
  level:
    org:
      hibernate: ERROR
      springframework:
        web: INFO
    guru:
      springframework:
        controllers: DEBUG
  file:
    name: logs/user-service.log
security:
  oauth2:
    client:
      client-secret: RobTheRich
      client-id: User-service
server:
  port: '8091'
  ssl:
    enabled: 'false'
